/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppQuotesIndexRouteImport } from './routes/_app.quotes.index'
import { Route as AppCatalogIndexRouteImport } from './routes/_app.catalog.index'
import { Route as AppQuotesQuoteIdRouteImport } from './routes/_app.quotes.$quoteId'
import { Route as AppCrmCustomersIndexRouteImport } from './routes/_app.crm.customers.index'
import { Route as AppCrmCustomersPipelineRouteImport } from './routes/_app.crm.customers.pipeline'
import { Route as AppCrmCustomersCustomerIdRouteImport } from './routes/_app.crm.customers.$customerId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotesIndexRoute = AppQuotesIndexRouteImport.update({
  id: '/quotes/',
  path: '/quotes/',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogIndexRoute = AppCatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotesQuoteIdRoute = AppQuotesQuoteIdRouteImport.update({
  id: '/quotes/$quoteId',
  path: '/quotes/$quoteId',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmCustomersIndexRoute = AppCrmCustomersIndexRouteImport.update({
  id: '/crm/customers/',
  path: '/crm/customers/',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmCustomersPipelineRoute = AppCrmCustomersPipelineRouteImport.update({
  id: '/crm/customers/pipeline',
  path: '/crm/customers/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmCustomersCustomerIdRoute =
  AppCrmCustomersCustomerIdRouteImport.update({
    id: '/crm/customers/$customerId',
    path: '/crm/customers/$customerId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/settings': typeof AppSettingsRoute
  '/quotes/$quoteId': typeof AppQuotesQuoteIdRoute
  '/catalog/': typeof AppCatalogIndexRoute
  '/quotes/': typeof AppQuotesIndexRoute
  '/crm/customers/$customerId': typeof AppCrmCustomersCustomerIdRoute
  '/crm/customers/pipeline': typeof AppCrmCustomersPipelineRoute
  '/crm/customers/': typeof AppCrmCustomersIndexRoute
}
export interface FileRoutesByTo {
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/quotes/$quoteId': typeof AppQuotesQuoteIdRoute
  '/catalog': typeof AppCatalogIndexRoute
  '/quotes': typeof AppQuotesIndexRoute
  '/crm/customers/$customerId': typeof AppCrmCustomersCustomerIdRoute
  '/crm/customers/pipeline': typeof AppCrmCustomersPipelineRoute
  '/crm/customers': typeof AppCrmCustomersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/quotes/$quoteId': typeof AppQuotesQuoteIdRoute
  '/_app/catalog/': typeof AppCatalogIndexRoute
  '/_app/quotes/': typeof AppQuotesIndexRoute
  '/_app/crm/customers/$customerId': typeof AppCrmCustomersCustomerIdRoute
  '/_app/crm/customers/pipeline': typeof AppCrmCustomersPipelineRoute
  '/_app/crm/customers/': typeof AppCrmCustomersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/quotes/$quoteId'
    | '/catalog/'
    | '/quotes/'
    | '/crm/customers/$customerId'
    | '/crm/customers/pipeline'
    | '/crm/customers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/settings'
    | '/'
    | '/quotes/$quoteId'
    | '/catalog'
    | '/quotes'
    | '/crm/customers/$customerId'
    | '/crm/customers/pipeline'
    | '/crm/customers'
  id:
    | '__root__'
    | '/_app'
    | '/_app/settings'
    | '/_app/'
    | '/_app/quotes/$quoteId'
    | '/_app/catalog/'
    | '/_app/quotes/'
    | '/_app/crm/customers/$customerId'
    | '/_app/crm/customers/pipeline'
    | '/_app/crm/customers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotes/': {
      id: '/_app/quotes/'
      path: '/quotes'
      fullPath: '/quotes/'
      preLoaderRoute: typeof AppQuotesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalog/': {
      id: '/_app/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof AppCatalogIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotes/$quoteId': {
      id: '/_app/quotes/$quoteId'
      path: '/quotes/$quoteId'
      fullPath: '/quotes/$quoteId'
      preLoaderRoute: typeof AppQuotesQuoteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/customers/': {
      id: '/_app/crm/customers/'
      path: '/crm/customers'
      fullPath: '/crm/customers/'
      preLoaderRoute: typeof AppCrmCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/customers/pipeline': {
      id: '/_app/crm/customers/pipeline'
      path: '/crm/customers/pipeline'
      fullPath: '/crm/customers/pipeline'
      preLoaderRoute: typeof AppCrmCustomersPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/customers/$customerId': {
      id: '/_app/crm/customers/$customerId'
      path: '/crm/customers/$customerId'
      fullPath: '/crm/customers/$customerId'
      preLoaderRoute: typeof AppCrmCustomersCustomerIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppQuotesQuoteIdRoute: typeof AppQuotesQuoteIdRoute
  AppCatalogIndexRoute: typeof AppCatalogIndexRoute
  AppQuotesIndexRoute: typeof AppQuotesIndexRoute
  AppCrmCustomersCustomerIdRoute: typeof AppCrmCustomersCustomerIdRoute
  AppCrmCustomersPipelineRoute: typeof AppCrmCustomersPipelineRoute
  AppCrmCustomersIndexRoute: typeof AppCrmCustomersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppQuotesQuoteIdRoute: AppQuotesQuoteIdRoute,
  AppCatalogIndexRoute: AppCatalogIndexRoute,
  AppQuotesIndexRoute: AppQuotesIndexRoute,
  AppCrmCustomersCustomerIdRoute: AppCrmCustomersCustomerIdRoute,
  AppCrmCustomersPipelineRoute: AppCrmCustomersPipelineRoute,
  AppCrmCustomersIndexRoute: AppCrmCustomersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
