/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppHrIndexRouteImport } from './routes/_app.hr.index'
import { Route as AppCrmIndexRouteImport } from './routes/_app.crm.index'
import { Route as AppHrEmployeesRouteImport } from './routes/_app.hr.employees'
import { Route as AppCrmQuotesIndexRouteImport } from './routes/_app.crm.quotes.index'
import { Route as AppCrmCustomersIndexRouteImport } from './routes/_app.crm.customers.index'
import { Route as AppCrmQuotesQuoteIdRouteImport } from './routes/_app.crm.quotes.$quoteId'
import { Route as AppCrmCustomersPipelineRouteImport } from './routes/_app.crm.customers.pipeline'
import { Route as AppCrmCustomersCustomerIdRouteImport } from './routes/_app.crm.customers.$customerId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppHrIndexRoute = AppHrIndexRouteImport.update({
  id: '/hr/',
  path: '/hr/',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmIndexRoute = AppCrmIndexRouteImport.update({
  id: '/crm/',
  path: '/crm/',
  getParentRoute: () => AppRoute,
} as any)
const AppHrEmployeesRoute = AppHrEmployeesRouteImport.update({
  id: '/hr/employees',
  path: '/hr/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmQuotesIndexRoute = AppCrmQuotesIndexRouteImport.update({
  id: '/crm/quotes/',
  path: '/crm/quotes/',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmCustomersIndexRoute = AppCrmCustomersIndexRouteImport.update({
  id: '/crm/customers/',
  path: '/crm/customers/',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmQuotesQuoteIdRoute = AppCrmQuotesQuoteIdRouteImport.update({
  id: '/crm/quotes/$quoteId',
  path: '/crm/quotes/$quoteId',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmCustomersPipelineRoute = AppCrmCustomersPipelineRouteImport.update({
  id: '/crm/customers/pipeline',
  path: '/crm/customers/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmCustomersCustomerIdRoute =
  AppCrmCustomersCustomerIdRouteImport.update({
    id: '/crm/customers/$customerId',
    path: '/crm/customers/$customerId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/settings': typeof AppSettingsRoute
  '/hr/employees': typeof AppHrEmployeesRoute
  '/crm/': typeof AppCrmIndexRoute
  '/hr/': typeof AppHrIndexRoute
  '/crm/customers/$customerId': typeof AppCrmCustomersCustomerIdRoute
  '/crm/customers/pipeline': typeof AppCrmCustomersPipelineRoute
  '/crm/quotes/$quoteId': typeof AppCrmQuotesQuoteIdRoute
  '/crm/customers/': typeof AppCrmCustomersIndexRoute
  '/crm/quotes/': typeof AppCrmQuotesIndexRoute
}
export interface FileRoutesByTo {
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/hr/employees': typeof AppHrEmployeesRoute
  '/crm': typeof AppCrmIndexRoute
  '/hr': typeof AppHrIndexRoute
  '/crm/customers/$customerId': typeof AppCrmCustomersCustomerIdRoute
  '/crm/customers/pipeline': typeof AppCrmCustomersPipelineRoute
  '/crm/quotes/$quoteId': typeof AppCrmQuotesQuoteIdRoute
  '/crm/customers': typeof AppCrmCustomersIndexRoute
  '/crm/quotes': typeof AppCrmQuotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/hr/employees': typeof AppHrEmployeesRoute
  '/_app/crm/': typeof AppCrmIndexRoute
  '/_app/hr/': typeof AppHrIndexRoute
  '/_app/crm/customers/$customerId': typeof AppCrmCustomersCustomerIdRoute
  '/_app/crm/customers/pipeline': typeof AppCrmCustomersPipelineRoute
  '/_app/crm/quotes/$quoteId': typeof AppCrmQuotesQuoteIdRoute
  '/_app/crm/customers/': typeof AppCrmCustomersIndexRoute
  '/_app/crm/quotes/': typeof AppCrmQuotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/hr/employees'
    | '/crm/'
    | '/hr/'
    | '/crm/customers/$customerId'
    | '/crm/customers/pipeline'
    | '/crm/quotes/$quoteId'
    | '/crm/customers/'
    | '/crm/quotes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/settings'
    | '/'
    | '/hr/employees'
    | '/crm'
    | '/hr'
    | '/crm/customers/$customerId'
    | '/crm/customers/pipeline'
    | '/crm/quotes/$quoteId'
    | '/crm/customers'
    | '/crm/quotes'
  id:
    | '__root__'
    | '/_app'
    | '/_app/settings'
    | '/_app/'
    | '/_app/hr/employees'
    | '/_app/crm/'
    | '/_app/hr/'
    | '/_app/crm/customers/$customerId'
    | '/_app/crm/customers/pipeline'
    | '/_app/crm/quotes/$quoteId'
    | '/_app/crm/customers/'
    | '/_app/crm/quotes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/': {
      id: '/_app/hr/'
      path: '/hr'
      fullPath: '/hr/'
      preLoaderRoute: typeof AppHrIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/': {
      id: '/_app/crm/'
      path: '/crm'
      fullPath: '/crm/'
      preLoaderRoute: typeof AppCrmIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr/employees': {
      id: '/_app/hr/employees'
      path: '/hr/employees'
      fullPath: '/hr/employees'
      preLoaderRoute: typeof AppHrEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/quotes/': {
      id: '/_app/crm/quotes/'
      path: '/crm/quotes'
      fullPath: '/crm/quotes/'
      preLoaderRoute: typeof AppCrmQuotesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/customers/': {
      id: '/_app/crm/customers/'
      path: '/crm/customers'
      fullPath: '/crm/customers/'
      preLoaderRoute: typeof AppCrmCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/quotes/$quoteId': {
      id: '/_app/crm/quotes/$quoteId'
      path: '/crm/quotes/$quoteId'
      fullPath: '/crm/quotes/$quoteId'
      preLoaderRoute: typeof AppCrmQuotesQuoteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/customers/pipeline': {
      id: '/_app/crm/customers/pipeline'
      path: '/crm/customers/pipeline'
      fullPath: '/crm/customers/pipeline'
      preLoaderRoute: typeof AppCrmCustomersPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/customers/$customerId': {
      id: '/_app/crm/customers/$customerId'
      path: '/crm/customers/$customerId'
      fullPath: '/crm/customers/$customerId'
      preLoaderRoute: typeof AppCrmCustomersCustomerIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppHrEmployeesRoute: typeof AppHrEmployeesRoute
  AppCrmIndexRoute: typeof AppCrmIndexRoute
  AppHrIndexRoute: typeof AppHrIndexRoute
  AppCrmCustomersCustomerIdRoute: typeof AppCrmCustomersCustomerIdRoute
  AppCrmCustomersPipelineRoute: typeof AppCrmCustomersPipelineRoute
  AppCrmQuotesQuoteIdRoute: typeof AppCrmQuotesQuoteIdRoute
  AppCrmCustomersIndexRoute: typeof AppCrmCustomersIndexRoute
  AppCrmQuotesIndexRoute: typeof AppCrmQuotesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppHrEmployeesRoute: AppHrEmployeesRoute,
  AppCrmIndexRoute: AppCrmIndexRoute,
  AppHrIndexRoute: AppHrIndexRoute,
  AppCrmCustomersCustomerIdRoute: AppCrmCustomersCustomerIdRoute,
  AppCrmCustomersPipelineRoute: AppCrmCustomersPipelineRoute,
  AppCrmQuotesQuoteIdRoute: AppCrmQuotesQuoteIdRoute,
  AppCrmCustomersIndexRoute: AppCrmCustomersIndexRoute,
  AppCrmQuotesIndexRoute: AppCrmQuotesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
