[package]
name = "handlers-reference"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
handlers = { workspace = true }
mestier-core = { workspace = true }
auth = { workspace = true }

axum = { workspace = true }
axum-extra = { workspace = true }
chrono = { workspace = true }
http = { workspace = true }
rust_decimal = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
utoipa = { workspace = true }
