[package]
name = "handlers-automation"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
handlers = { workspace = true }
mestier-core = { workspace = true }
auth = { workspace = true }

axum = { workspace = true }
axum-extra = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
utoipa = { workspace = true }
uuid = { workspace = true }
