{{- if .Values.api.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mestier.fullname" . }}-api
  labels:
    {{- include "mestier.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
data:
  {{- range $key, $value := .Values.api.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
