{{- if and .Values.api.enabled .Values.api.secret.create (not .Values.api.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mestier.api.secretName" . }}
  labels:
    {{- include "mestier.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
type: Opaque
stringData:
  {{- if and (not (index .Values.api.secret.valueFrom "DATABASE_PASSWORD")) .Values.api.secret.DATABASE_PASSWORD }}
  DATABASE_PASSWORD: {{ .Values.api.secret.DATABASE_PASSWORD | quote }}
  {{- end }}
  {{- if and (not (index .Values.api.secret.valueFrom "AUTH_CLIENT_SECRET")) .Values.api.secret.AUTH_CLIENT_SECRET }}
  AUTH_CLIENT_SECRET: {{ .Values.api.secret.AUTH_CLIENT_SECRET | quote }}
  {{- end }}
  {{- if and (not (index .Values.api.secret.valueFrom "FILE_STORAGE_ACCESS_KEY_ID")) .Values.api.secret.FILE_STORAGE_ACCESS_KEY_ID }}
  FILE_STORAGE_ACCESS_KEY_ID: {{ .Values.api.secret.FILE_STORAGE_ACCESS_KEY_ID | quote }}
  {{- end }}
  {{- if and (not (index .Values.api.secret.valueFrom "FILE_STORAGE_SECRET_ACCESS_KEY")) .Values.api.secret.FILE_STORAGE_SECRET_ACCESS_KEY }}
  FILE_STORAGE_SECRET_ACCESS_KEY: {{ .Values.api.secret.FILE_STORAGE_SECRET_ACCESS_KEY | quote }}
  {{- end }}
  {{- if and (not (index .Values.api.secret.valueFrom "AUTOMATION_SECRET_KEY")) .Values.api.secret.AUTOMATION_SECRET_KEY }}
  AUTOMATION_SECRET_KEY: {{ .Values.api.secret.AUTOMATION_SECRET_KEY | quote }}
  {{- end }}
{{- end }}
