import {
	Boxes,
	BriefcaseBusiness,
	CalendarDays,
	CalendarOff,
	CalendarRange,
	Clock,
	FileText,
	FileWarning,
	FolderKanban,
	KanbanSquare,
	LayoutDashboard,
	LayoutTemplate,
	ListTree,
	MessagesSquare,
	Package,
	Receipt,
	Settings,
	ShoppingCart,
	TrendingUp,
	Users,
} from 'lucide-react'
import type { AppModule } from '#/modules/types'

export const MODULES: AppModule[] = [
	{
		id: 'home',
		label: 'Accueil',
		icon: LayoutDashboard,
		basePath: '/',
		status: 'available',
		hasOverview: true,
		sections: [
			{
				id: 'overview',
				label: 'Vue d’ensemble',
				to: '/',
				icon: LayoutDashboard,
				exact: true,
			},
			{
				id: 'profitability',
				label: 'Rentabilité',
				to: '/reporting',
				icon: TrendingUp,
				requiredPermission: 'VIEW_REPORTS',
			},
		],
	},
	{
		id: 'crm',
		label: 'CRM',
		icon: Users,
		basePath: '/crm',
		status: 'available',
		hasOverview: false,
		sections: [
			{
				id: 'customers',
				label: 'Clients',
				to: '/crm/customers',
				icon: Users,
				exact: true,
				requiredPermission: 'VIEW_CUSTOMERS',
			},
			{
				id: 'pipeline',
				label: 'Pipeline',
				to: '/crm/customers/pipeline',
				icon: KanbanSquare,
				requiredPermission: 'VIEW_CUSTOMERS',
			},
			{
				id: 'quotes',
				label: 'Devis',
				to: '/crm/quotes',
				icon: FileText,
				requiredPermission: 'MANAGE_QUOTES',
			},
			{
				id: 'invoices',
				label: 'Factures',
				to: '/crm/invoices',
				icon: Receipt,
				requiredPermission: 'VIEW_INVOICES',
			},
			{
				id: 'catalog',
				label: 'Catalogue',
				to: '/crm/catalog',
				icon: Boxes,
				requiredPermission: 'MANAGE_REFERENCE',
			},
		],
	},
	{
		id: 'purchase',
		label: 'Achats',
		icon: ShoppingCart,
		basePath: '/purchase',
		status: 'available',
		hasOverview: false,
		sections: [
			{
				id: 'supplier-invoices',
				label: 'Factures fournisseurs',
				to: '/purchase/supplier-invoices',
				icon: FileWarning,
			},
		],
	},
	{
		id: 'hr',
		label: 'Équipe & ressources',
		icon: BriefcaseBusiness,
		basePath: '/hr',
		status: 'available',
		hasOverview: false,
		sections: [
			{
				id: 'team',
				label: 'Équipe',
				to: '/hr/team',
				icon: Users,
				requiredPermission: 'MANAGE_MEMBERS',
			},
			{
				id: 'work-time',
				label: 'Temps de travail',
				to: '/hr/work-time',
				icon: Clock,
				requiredPermission: 'MANAGE_PLANNING',
			},
			{
				id: 'absences',
				label: 'Absences',
				to: '/hr/absences',
				icon: CalendarOff,
				requiredPermission: 'MANAGE_REFERENCE',
			},
			{
				id: 'equipment',
				label: 'Matériel',
				to: '/hr/equipment',
				icon: Package,
				requiredPermission: 'MANAGE_REFERENCE',
			},
		],
	},
	{
		id: 'planning',
		label: 'Planning',
		icon: CalendarRange,
		basePath: '/planning',
		status: 'available',
		hasOverview: false,
		sections: [
			{
				id: 'calendar',
				label: 'Calendrier',
				to: '/planning/calendar',
				icon: CalendarDays,
			},
			{
				id: 'team',
				label: 'Vue équipe',
				to: '/planning/team',
				icon: CalendarRange,
			},
			{
				id: 'tasks',
				label: 'Liste des tâches',
				to: '/planning/tasks',
				icon: ListTree,
			},
			{
				id: 'projects',
				label: 'Projets',
				to: '/planning/projects',
				icon: FolderKanban,
			},
			{
				id: 'project-templates',
				label: 'Modèles de projet',
				to: '/planning/project-templates',
				icon: LayoutTemplate,
			},
			{
				id: 'reports',
				label: 'Écarts signalés',
				to: '/planning/reports',
				icon: FileWarning,
			},
		],
	},
	{
		id: 'chat',
		label: 'Discussions',
		icon: MessagesSquare,
		basePath: '/chat',
		status: 'available',
		hasOverview: true,
		sections: [
			{
				id: 'channels',
				label: 'Canaux',
				to: '/chat',
				icon: MessagesSquare,
			},
		],
	},
	{
		id: 'settings',
		label: 'Paramètres',
		icon: Settings,
		basePath: '/settings',
		status: 'available',
		hasOverview: true,
		railPlacement: 'utility',
		sections: [
			{
				id: 'organisation',
				label: 'Organisation',
				to: '/settings',
				exact: true,
			},
		],
	},
]
