[package]
name = "common"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
thiserror = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
serde = { workspace = true }
utoipa = { workspace = true }
hmac = { workspace = true }
sha2 = { workspace = true }
hex = "0.4"
