apiVersion: v2
name: mestier
description: Mestier ERP — API and webapp
type: application
version: 0.5.0
appVersion: "0.1.0"
home: https://github.com/ferrislabs/mestier
sources:
  - https://github.com/ferrislabs/mestier
keywords:
  - erp
  - artisans
