use utoipa::{
    Modify, OpenApi,
    openapi::security::{HttpAuthScheme, HttpBuilder, SecurityScheme},
};

use handlers_customer as customer;
use handlers_discord as discord;
use handlers_files as files;
use handlers_invoice as invoice;
use handlers_organization as organization;
use handlers_quote as quote;
use handlers_reference as reference;

pub struct SecurityAddon;

impl Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        let components = openapi.components.get_or_insert_with(Default::default);
        components.add_security_scheme(
            "bearer_auth",
            SecurityScheme::Http(
                HttpBuilder::new()
                    .scheme(HttpAuthScheme::Bearer)
                    .bearer_format("JWT")
                    .build(),
            ),
        );
    }
}

#[derive(OpenApi)]
#[openapi(
    info(title = "Mestier API", description = "API for Mestier", version = "0.1.0"),
    paths(
        files::upload::handler,
        customer::customer::create::handler,
        customer::customer::list::handler,
        customer::customer::get_one::handler,
        customer::customer::update::handler,
        customer::customer::soft_delete::handler,
        customer::customer_contact::create::handler,
        customer::customer_contact::list::handler,
        customer::customer_contact::get_one::handler,
        customer::customer_contact::update::handler,
        customer::customer_contact::soft_delete::handler,
        customer::customer_context::create::handler,
        customer::customer_context::list::handler,
        customer::customer_context::get_one::handler,
        customer::customer_context::update::handler,
        customer::customer_context::soft_delete::handler,
        organization::create::handler,
        organization::list::handler,
        organization::list_mine::handler,
        organization::get_one::handler,
        organization::update::handler,
        organization::soft_delete::handler,
        invoice::invoice::create::handler,
        invoice::invoice::list::handler,
        invoice::invoice::get_one::handler,
        invoice::invoice::update::handler,
        invoice::invoice::update_status::handler,
        invoice::invoice::soft_delete::handler,
        invoice::invoice::convert_from_quote::handler,
        quote::quote::create::handler,
        quote::quote::list::handler,
        quote::quote::get_one::handler,
        quote::quote::update::handler,
        quote::quote::update_status::handler,
        quote::quote::soft_delete::handler,
        quote::quote::export_pdf::handler,
        reference::employee::create::handler,
        reference::employee::list::handler,
        reference::employee::get_one::handler,
        reference::employee::update::handler,
        reference::employee::soft_delete::handler,
        reference::equipment::create::handler,
        reference::equipment::list::handler,
        reference::equipment::get_one::handler,
        reference::equipment::update::handler,
        reference::equipment::soft_delete::handler,
        reference::service_rate::create::handler,
        reference::service_rate::list::handler,
        reference::service_rate::get_one::handler,
        reference::service_rate::update::handler,
        reference::service_rate::soft_delete::handler,
        reference::product::create::handler,
        reference::product::list::handler,
        reference::product::get_one::handler,
        reference::product::update::handler,
        reference::product::soft_delete::handler,
        reference::billing_settings::get::handler,
        reference::billing_settings::upsert::handler,
        reference::legal_mention_template::create::handler,
        reference::legal_mention_template::list::handler,
        reference::legal_mention_template::update::handler,
        reference::legal_mention_template::soft_delete::handler,
        discord::category::list::handler,
        discord::category::create::handler,
        discord::category::update::handler,
        discord::category::delete::handler,
        discord::channel::list::handler,
        discord::channel::create::handler,
        discord::channel::get_one::handler,
        discord::channel::update::handler,
        discord::channel::delete::handler,
        discord::thread::list::handler,
        discord::thread::create::handler,
        discord::thread::update::handler,
        discord::thread::delete::handler,
        discord::message::list::handler,
        discord::message::create::handler,
        discord::message::update::handler,
        discord::message::delete::handler,
        discord::reaction::add::handler,
        discord::reaction::remove::handler,
        discord::reaction::list::handler,
        discord::webhook::list::handler,
        discord::webhook::create::handler,
        discord::webhook::update::handler,
        discord::webhook::delete::handler,
        discord::webhook::execute::handler,
        discord::presence::set::handler,
        discord::typing::start::handler,
        discord::read_state::mark::handler,
        discord::read_state::unread::handler,
        discord::channel::permissions::list::handler,
        discord::channel::permissions::upsert_everyone::handler,
        discord::channel::permissions::upsert_target::handler,
        discord::channel::permissions::delete_everyone::handler,
        discord::channel::permissions::delete_target::handler,
        discord::notification::list::handler,
        discord::notification::mark_read::handler,
        discord::notification::mark_all_read::handler,
    ),
    components(schemas(
        organization::create::CreateOrganizationRequest,
        organization::update::UpdateOrganizationRequest,
        organization::response::OrganizationResponse,
        files::response::FileUploadResponse,
        customer::customer::create::CreateCustomerRequest,
        customer::customer::update::UpdateCustomerRequest,
        customer::customer_contact::create::CreateCustomerContactRequest,
        customer::customer_contact::update::UpdateCustomerContactRequest,
        customer::customer_context::create::CreateCustomerContextRequest,
        customer::customer_context::update::UpdateCustomerContextRequest,
        customer::response::CustomerResponse,
        customer::response::CustomerContactResponse,
        customer::response::CustomerContextResponse,
        invoice::invoice::create::CreateInvoiceRequest,
        invoice::invoice::create::InvoiceLineRequest,
        invoice::invoice::update::UpdateInvoiceRequest,
        invoice::invoice::update_status::UpdateInvoiceStatusRequest,
        invoice::response::InvoiceLineResponse,
        invoice::response::InvoiceResponse,
        quote::quote::create::CreateQuoteRequest,
        quote::quote::create::QuoteLineRequest,
        quote::quote::update::UpdateQuoteRequest,
        quote::quote::update_status::UpdateQuoteStatusRequest,
        quote::response::QuoteLineResponse,
        quote::response::QuoteResponse,
        reference::employee::create::CreateEmployeeRequest,
        reference::employee::update::UpdateEmployeeRequest,
        reference::equipment::create::CreateEquipmentRequest,
        reference::equipment::update::UpdateEquipmentRequest,
        reference::service_rate::create::CreateServiceRateRequest,
        reference::service_rate::update::UpdateServiceRateRequest,
        reference::product::create::CreateProductRequest,
        reference::product::update::UpdateProductRequest,
        reference::billing_settings::upsert::UpsertBillingSettingsRequest,
        reference::legal_mention_template::create::CreateLegalMentionTemplateRequest,
        reference::legal_mention_template::update::UpdateLegalMentionTemplateRequest,
        reference::response::EmployeeResponse,
        reference::response::EquipmentResponse,
        reference::response::ServiceRateResponse,
        reference::response::ProductResponse,
        reference::response::BillingSettingsResponse,
        reference::response::LegalMentionTemplateResponse,
        discord::category::create::CreateCategoryRequest,
        discord::category::update::UpdateCategoryRequest,
        discord::channel::create::CreateChannelRequest,
        discord::channel::update::UpdateChannelRequest,
        discord::thread::create::CreateThreadRequest,
        discord::thread::update::UpdateThreadRequest,
        discord::message::create::CreateMessageRequest,
        discord::message::create::CreateMessageAttachment,
        discord::message::update::UpdateMessageRequest,
        discord::webhook::create::CreateWebhookRequest,
        discord::webhook::update::UpdateWebhookRequest,
        discord::webhook::execute::ExecuteWebhookRequest,
        discord::presence::set::SetPresenceRequest,
        discord::read_state::mark::MarkChannelReadRequest,
        discord::response::CategoryResponse,
        discord::response::ChannelResponse,
        discord::response::MessageResponse,
        discord::response::AttachmentResponse,
        discord::response::ReactionCountResponse,
        discord::response::WebhookResponse,
        discord::response::WebhookCreatedResponse,
        discord::response::PresenceResponse,
        discord::read_state::unread::UnreadResponse,
        discord::response::OverwriteResponse,
        discord::response::UpsertOverwriteRequest,
        discord::notification::list::NotificationResponse,
    )),
    modifiers(&SecurityAddon),
    tags(
        (name = "organizations", description = "Organizations management"),
        (name = "files", description = "File uploads and storage"),
        (name = "customers", description = "Customers and customer contexts management"),
        (name = "invoices", description = "Invoices and invoice lines management"),
        (name = "quotes", description = "Quotes and quote lines management"),
        (name = "reference", description = "Reference cost catalog"),
        (name = "discord", description = "Chat — categories, channels, threads, messages, reactions, webhooks, presence, typing, read states, channel permission overwrites, notifications"),
    )
)]
pub struct ApiDoc;
