use utoipa::{
    Modify, OpenApi,
    openapi::security::{HttpAuthScheme, HttpBuilder, SecurityScheme},
};

use handlers_automation as automation;
use handlers_customer as customer;
use handlers_discord as discord;
use handlers_field as field;
use handlers_files as files;
use handlers_member as member;
use handlers_organization as organization;
use handlers_planning as planning;
use handlers_quote as quote;
use handlers_reference as reference;

pub struct SecurityAddon;

impl Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        let components = openapi.components.get_or_insert_with(Default::default);
        components.add_security_scheme(
            "bearer_auth",
            SecurityScheme::Http(
                HttpBuilder::new()
                    .scheme(HttpAuthScheme::Bearer)
                    .bearer_format("JWT")
                    .build(),
            ),
        );
    }
}

#[derive(OpenApi)]
#[openapi(
    info(title = "Mestier API", description = "API for Mestier", version = "0.1.0"),
    paths(
        automation::catalogue::connectors,
        automation::catalogue::events,
        automation::credential::list::handler,
        automation::credential::create::handler,
        automation::credential::update::handler,
        automation::credential::delete::handler,
        automation::credential::rotate::handler,
        automation::workflow::list::handler,
        automation::workflow::create::handler,
        automation::workflow::get_one::handler,
        automation::workflow::update::handler,
        automation::workflow::delete::handler,
        automation::workflow::save_version::handler,
        automation::run::list::handler,
        automation::run::get_one::handler,
        automation::run::replay::handler,
        automation::run::start::handler,
        automation::settings::get,
        automation::settings::put,
        field::field::my_tasks::handler,
        field::field::current::handler,
        field::field::start::handler,
        field::field::stop::handler,
        field::field::attach_photo::handler,
        field::field::end_day::handler,
        files::upload::handler,
        files::url::handler,
        customer::customer::create::handler,
        customer::customer::list::handler,
        customer::customer::get_one::handler,
        customer::customer::update::handler,
        customer::customer::soft_delete::handler,
        customer::customer_contact::create::handler,
        customer::customer_contact::list::handler,
        customer::customer_contact::get_one::handler,
        customer::customer_contact::update::handler,
        customer::customer_contact::soft_delete::handler,
        customer::customer_context::create::handler,
        customer::customer_context::list::handler,
        customer::customer_context::get_one::handler,
        customer::customer_context::update::handler,
        customer::customer_context::soft_delete::handler,
        member::member::list::handler,
        member::member::create::handler,
        member::member::get_one::handler,
        member::member::update::handler,
        member::member::soft_delete::handler,
        member::invitation::create::handler,
        member::invitation::list::handler,
        member::invitation::revoke::handler,
        member::invitation::accept::handler,
        organization::create::handler,
        organization::list::handler,
        organization::list_mine::handler,
        organization::get_one::handler,
        organization::update::handler,
        organization::soft_delete::handler,
        quote::quote::create::handler,
        quote::quote::list::handler,
        quote::quote::get_one::handler,
        quote::quote::update::handler,
        quote::quote::update_status::handler,
        quote::quote::soft_delete::handler,
        quote::quote::export_pdf::handler,
        reference::employee::list::handler,
        reference::employee::upsert_profile::handler,
        reference::employee::remove_profile::handler,
        reference::equipment::create::handler,
        reference::equipment::list::handler,
        reference::equipment::get_one::handler,
        reference::equipment::update::handler,
        reference::equipment::soft_delete::handler,
        reference::service_rate::create::handler,
        reference::service_rate::list::handler,
        reference::service_rate::get_one::handler,
        reference::service_rate::update::handler,
        reference::service_rate::soft_delete::handler,
        reference::product::create::handler,
        reference::product::list::handler,
        reference::product::get_one::handler,
        reference::product::update::handler,
        reference::product::soft_delete::handler,
        planning::task::create::handler,
        planning::task::list::handler,
        planning::task::get_one::handler,
        planning::task::update::handler,
        planning::task::soft_delete::handler,
        planning::task::bulk_assign::handler,
        planning::task_label::create::handler,
        planning::task_label::list::handler,
        planning::task_label::update::handler,
        planning::task_label::delete::handler,
        planning::task_comment::list::handler,
        planning::task_comment::create::handler,
        planning::task_comment::update::handler,
        planning::task_comment::delete::handler,
        reference::absence::create::handler,
        reference::absence::list::handler,
        reference::absence::update::handler,
        reference::absence::soft_delete::handler,
        planning::work_time::get_work_time::handler,
        planning::work_time::put_rhythm::handler,
        planning::work_time::put_work_slots::handler,
        planning::planning::get_planning::handler,
        planning::planning::get_availability::handler,
        discord::category::list::handler,
        discord::category::create::handler,
        discord::category::update::handler,
        discord::category::delete::handler,
        discord::channel::list::handler,
        discord::channel::create::handler,
        discord::channel::get_one::handler,
        discord::channel::update::handler,
        discord::channel::delete::handler,
        discord::thread::list::handler,
        discord::thread::create::handler,
        discord::thread::update::handler,
        discord::thread::delete::handler,
        discord::message::list::handler,
        discord::message::create::handler,
        discord::message::update::handler,
        discord::message::delete::handler,
        discord::reaction::add::handler,
        discord::reaction::remove::handler,
        discord::reaction::list::handler,
        discord::webhook::list::handler,
        discord::webhook::create::handler,
        discord::webhook::update::handler,
        discord::webhook::delete::handler,
        discord::webhook::execute::handler,
        discord::presence::set::handler,
        discord::typing::start::handler,
        discord::read_state::mark::handler,
        discord::read_state::unread::handler,
        discord::channel::permissions::list::handler,
        discord::channel::permissions::upsert_everyone::handler,
        discord::channel::permissions::upsert_target::handler,
        discord::channel::permissions::delete_everyone::handler,
        discord::channel::permissions::delete_target::handler,
        discord::notification::list::handler,
        discord::notification::mark_read::handler,
        discord::notification::mark_all_read::handler,
    ),
    components(schemas(
        automation::credential::create::CreateCredentialRequest,
        automation::credential::create::CredentialOriginRequest,
        automation::credential::update::UpdateCredentialRequest,
        automation::workflow::create::CreateWorkflowRequest,
        automation::workflow::update::UpdateWorkflowRequest,
        automation::workflow::save_version::SaveWorkflowVersionRequest,
        automation::workflow::save_version::GraphInvalidBody,
        automation::workflow::save_version::GraphInvalidDetails,
        automation::run::replay::ReplayRunRequest,
        automation::run::start::StartRunRequest,
        automation::run::start::StartedRunResponse,
        automation::response::CredentialResponse,
        automation::response::CredentialWithSecretResponse,
        automation::response::ConnectorsResponse,
        automation::response::ConnectorDescriptorResponse,
        automation::response::AuthSchemeResponse,
        automation::response::FieldResponse,
        automation::response::FieldKindResponse,
        automation::response::SelectOptionResponse,
        automation::response::VisibleWhenResponse,
        automation::response::AuthRequirementResponse,
        automation::response::EventDescriptorResponse,
        automation::response::WorkflowResponse,
        automation::response::WorkflowDetailResponse,
        automation::response::WorkflowVersionResponse,
        automation::response::GraphDto,
        automation::response::PlacedConnectorDto,
        automation::response::EdgeDto,
        automation::response::BranchDto,
        automation::response::GraphErrorResponse,
        automation::response::RunResponse,
        automation::response::RunDetailResponse,
        automation::response::RunStepResponse,
        automation::response::AutomationSettingsBody,
        organization::create::CreateOrganizationRequest,
        organization::update::UpdateOrganizationRequest,
        organization::response::OrganizationResponse,
        field::response::FieldTaskResponse,
        field::response::TimeEntryResponse,
        field::response::TimeEntryPhotoResponse,
        field::response::DayLogResponse,
        field::field::start::StartTimeEntryRequest,
        field::field::attach_photo::AttachPhotoRequest,
        field::field::end_day::EndDayRequest,
        files::response::FileUploadResponse,
        files::response::FileUrlResponse,
        customer::customer::create::CreateCustomerRequest,
        customer::customer::update::UpdateCustomerRequest,
        customer::customer_contact::create::CreateCustomerContactRequest,
        customer::customer_contact::update::UpdateCustomerContactRequest,
        customer::customer_context::create::CreateCustomerContextRequest,
        customer::customer_context::update::UpdateCustomerContextRequest,
        customer::response::CustomerResponse,
        customer::response::CustomerContactResponse,
        customer::response::CustomerContextResponse,
        quote::quote::create::CreateQuoteRequest,
        quote::quote::create::QuoteLineRequest,
        quote::quote::update::UpdateQuoteRequest,
        quote::quote::update_status::UpdateQuoteStatusRequest,
        quote::response::QuoteLineResponse,
        quote::response::QuoteResponse,
        member::member::create::CreateMemberRequest,
        member::member::update::UpdateMemberRequest,
        member::response::MemberResponse,
        member::response::MemberAccountResponse,
        member::invitation::create::CreateInvitationRequest,
        member::response::InvitationResponse,
        member::response::CreatedInvitationResponse,
        reference::employee::upsert_profile::UpsertEmployeeProfileRequest,
        reference::equipment::create::CreateEquipmentRequest,
        reference::equipment::update::UpdateEquipmentRequest,
        reference::service_rate::create::CreateServiceRateRequest,
        reference::service_rate::update::UpdateServiceRateRequest,
        reference::product::create::CreateProductRequest,
        reference::product::update::UpdateProductRequest,
        planning::task::create::CreateTaskRequest,
        planning::task::update::UpdateTaskRequest,
        planning::task::bulk_assign::BulkAssignTasksRequest,
        planning::response::TaskResponse,
        planning::response::BulkAssignTasksResponse,
        planning::task_label::create::CreateTaskLabelRequest,
        planning::task_label::update::UpdateTaskLabelRequest,
        planning::task_label::TaskLabelResponse,
        planning::task_comment::create::CreateTaskCommentRequest,
        planning::task_comment::update::UpdateTaskCommentRequest,
        planning::task_comment::TaskCommentResponse,
        planning::response::PatchTaskResponse,
        reference::absence::create::CreateAbsenceRequest,
        reference::absence::update::UpdateAbsenceRequest,
        reference::absence::AbsenceResponse,
        planning::work_time::RhythmResponse,
        planning::work_time::RhythmSlotResponse,
        planning::work_time::WorkSlotResponse,
        planning::work_time::WorkTimeResponse,
        planning::work_time::put_rhythm::PutRhythmRequest,
        planning::work_time::put_rhythm::RhythmSlotRequest,
        planning::work_time::put_work_slots::PutWorkSlotsRequest,
        planning::work_time::put_work_slots::WorkSlotRequest,
        planning::planning::get_planning::PlanningResourceResponse,
        planning::planning::get_planning::PlanningEntryResponse,
        planning::planning::get_planning::MinuteIntervalResponse,
        planning::planning::get_planning::PlanningWorkTimeDayResponse,
        planning::planning::get_planning::PlanningWorkTimeResponse,
        planning::planning::get_planning::PlanningResponse,
        planning::planning::get_availability::ConflictResponse,
        planning::planning::get_availability::AvailabilityResourceResponse,
        planning::planning::get_availability::AvailabilityResponse,
        // `planning::response::EmployeeResponse` is deliberately absent: it is
        // byte-identical to `reference::response::EmployeeResponse` above, and
        // utoipa names schemas after the type, so registering both would
        // collide. See the PR description — if the two ever diverge, this
        // document starts describing the wrong shape silently.
        reference::response::EmployeeResponse,
        reference::response::EquipmentResponse,
        reference::response::ServiceRateResponse,
        reference::response::ProductResponse,
        discord::category::create::CreateCategoryRequest,
        discord::category::update::UpdateCategoryRequest,
        discord::channel::create::CreateChannelRequest,
        discord::channel::update::UpdateChannelRequest,
        discord::thread::create::CreateThreadRequest,
        discord::thread::update::UpdateThreadRequest,
        discord::message::create::CreateMessageRequest,
        discord::message::create::CreateMessageAttachment,
        discord::message::update::UpdateMessageRequest,
        discord::webhook::create::CreateWebhookRequest,
        discord::webhook::update::UpdateWebhookRequest,
        discord::webhook::execute::ExecuteWebhookRequest,
        discord::presence::set::SetPresenceRequest,
        discord::read_state::mark::MarkChannelReadRequest,
        discord::response::CategoryResponse,
        discord::response::ChannelResponse,
        discord::response::MessageResponse,
        discord::response::AttachmentResponse,
        discord::response::ReactionCountResponse,
        discord::response::WebhookResponse,
        discord::response::WebhookCreatedResponse,
        discord::response::PresenceResponse,
        discord::read_state::unread::UnreadResponse,
        discord::response::OverwriteResponse,
        discord::response::UpsertOverwriteRequest,
        discord::notification::list::NotificationResponse,
    )),
    modifiers(&SecurityAddon),
    tags(
        (name = "automation", description = "Workflow engine — connector and event catalogues, credentials, workflows, runs, settings"),
        (name = "organizations", description = "Organizations management"),
        (name = "field", description = "Field app: clocking on and off, day end"),
        (name = "files", description = "File uploads and storage"),
        (name = "customers", description = "Customers and customer contexts management"),
        (name = "quotes", description = "Quotes and quote lines management"),
        (name = "members", description = "Organization seats — free or occupied, no account required"),
        (name = "reference", description = "Reference cost catalog"),
        (name = "planning", description = "Team planning — tasks, assignments, working time and availability"),
        (name = "discord", description = "Chat — categories, channels, threads, messages, reactions, webhooks, presence, typing, read states, channel permission overwrites, notifications"),
    )
)]
pub struct ApiDoc;
