[package]
name = "mestier-core"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
common = { workspace = true }
discord = { workspace = true }
events = { workspace = true }
auth = { workspace = true }
authz = { workspace = true }
mestier-macros = { workspace = true }
rate-limit = { workspace = true }

uuid = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
utoipa = { workspace = true }
chrono = { workspace = true }
chrono-tz = { workspace = true }
sqlx = { workspace = true }
rust_decimal = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
tracing = { workspace = true }
aws-credential-types = { workspace = true }
aws-sdk-s3 = { workspace = true }
bytes = { workspace = true }

[dev-dependencies]
authz = { workspace = true, features = ["mock"] }
mockall = { workspace = true }
tokio = { workspace = true, features = ["time"] }
